spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/loginTest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true
server:
  servlet:
    session:
      timeout: 60
      tracking-modes: cookie

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace