spring:
  datasource:
    url: jdbc:mysql://basketball-diary.comugfwcpzzw.ap-northeast-2.rds.amazonaws.com/basketDiary
    username: admin
    password: Basket5199

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true
server:
  servlet:
    session:
      timeout: 60
      tracking-modes: cookie

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace